const dadoA = prompt("Nome completo")
const dadoB = prompt("Data de nascimento (utilize /)")
const dadoC = prompt("Endereço")
const dadoD = Number(prompt("CPF"))
const dadoE = prompt("Escolaridade")
const dadoF = prompt("Possui CNH?")
const dadoG = Number(prompt("Quantos filhes possui?"))
const dadoH = prompt("Cargo atual")
const dadoI = Number(prompt("Salário"))
const dadoJ = prompt("Recebe comissão? Se sim, informe a porcentagem, caso não, responda com zero")
const dadoK = Number(prompt("Informe o ano de admissão"))

console.log("Nome do colaborador:" , dadoA)
console.log("Data de nascimento:" , dadoB)
console.log("Reside em:" , dadoC)
console.log("Portador do CPF Número:" , dadoD)
console.log("Escolaridade:", dadoE)
console.log("CNH:", dadoF)
console.log("Filhes:",  dadoG)
console.log("Cargo:" , dadoH)
console.log("Salário:" , dadoI)
console.log("Comissão:" , dadoJ)
console.log("Ano de admissão:" ,  dadoK)

